#!/usr/bin/python
# -*- coding: utf-8 -*-

# This script retrieves data about the use of properties on Wikidata from
# SPARQL. The results are processed and stored in the file properties.json.
# The script must be run in a directory that already contains these files
# (possibly with no content other than an empty map {}). Normally, the files
# are first generated by the Java export tool, which provides some statistics
# that cannot be obtained in an acceptable time from SPARQL.

import dataUpdate as up

up.updatePropertyRecords()
print "Done."

