#!/usr/bin/python
# -*- coding: utf-8 -*-

# This script retrieves data about the use of classes on Wikidata from
# SPARQL. The results are processed and stored in the file classes.json.
# The script must be run in a directory that already contains this file
# (possibly with no content other than an empty map {}). Normally, the file
# is first generated by the Java export tool, which provides some statistics
# that cannot be obtained in an acceptable time from SPARQL.

import dataUpdate as up

up.updateRules()
